# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2017, 8, 27, 6, 24, 53, 734883, tzinfo=utc))),
            ],
        ),
    ]
